### ISSUE TITLE
Make the installation directory independent

### ISSUE THREAD

**Issue by berdav** [therealsaumil/armx#7]
Hi,
if I understood it correctly, the project relies on the installation within a root dir called "armx".

I think that it would be better to make it configurable, for example by using relative path in scripts or detect project root.
This last step could be made using bash path detection such as
```bash
PROJECT_ROOT_DIR="$(cd $(dirname $0) ; pwd)"
```

Are you interested in this enhancement?

**Comment by therealsaumil** [comment]
Hi Davide, I have pondered this for a very very long time. Unfortunately there are several dependencies for `/armx`. First, the host system has to export `/armx` via NFS, so that the booted up QEMU images can mount it with their environments. Changing this path will not only require changes to the shell scripts (which is what you have indicated), however, it will require changes to the Buildroot environment which is responsible for `hostfs.ext2` and the NFS server paths in the Preview VM. For now, I am leaving `/armx` as is - hardcoded  :(
